# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: '$(Build.Repository.LocalPath)'
    FodConnection: 'AzuredevopsApi'    # create Azure DevOps Service connection with name FoD_AMS
    ReleaseOptions: '0'
    ReleaseId: 1308133            # update FoD RELEASE ID
    EntitlementSelection: '1'
    EntitlementPreference: '0'
    OverrideScanSettings: '1'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'mvn'
    TechnologyStackJavaOne: '17'
    PolicyFailAction: '0'
